export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  BRANCH_MANAGER = 'BRANCH_MANAGER',
  ADMIN = 'ADMIN',
  SALES = 'SALES',
  TECHNICIAN = 'TECHNICIAN',
  FINANCE = 'FINANCE',
}

export enum PropertyType {
  RESIDENTIAL = 'RESIDENTIAL',
  COMMERCIAL = 'COMMERCIAL',
  INDUSTRIAL = 'INDUSTRIAL',
}

export enum CustomerStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum LeadSource {
  FACEBOOK = 'FACEBOOK',
  GOOGLE = 'GOOGLE',
  REFERRAL = 'REFERRAL',
  WEBSITE = 'WEBSITE',
  WALK_IN = 'WALK_IN',
  COLD_CALL = 'COLD_CALL',
  OTHER = 'OTHER',
}

export enum LeadStage {
  NEW_LEAD = 'NEW_LEAD',
  CONTACTED = 'CONTACTED',
  SITE_INSPECTION = 'SITE_INSPECTION',
  QUOTATION_SENT = 'QUOTATION_SENT',
  NEGOTIATION = 'NEGOTIATION',
  CLOSED_WON = 'CLOSED_WON',
  CLOSED_LOST = 'CLOSED_LOST',
}

export enum QuotationStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  SENT = 'SENT',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum PricingType {
  FIXED = 'FIXED',
  PER_SQFT = 'PER_SQFT',
  PER_UNIT = 'PER_UNIT',
  PER_VISIT = 'PER_VISIT',
  PACKAGE = 'PACKAGE',
}

export enum JobStatus {
  SCHEDULED = 'SCHEDULED',
  EN_ROUTE = 'EN_ROUTE',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  RESCHEDULED = 'RESCHEDULED',
}

export enum JobPriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  EMERGENCY = 'EMERGENCY',
}

export enum RecurringFrequency {
  WEEKLY = 'WEEKLY',
  BIWEEKLY = 'BIWEEKLY',
  MONTHLY = 'MONTHLY',
  BIMONTHLY = 'BIMONTHLY',
  QUARTERLY = 'QUARTERLY',
  BIANNUALLY = 'BIANNUALLY',
  ANNUALLY = 'ANNUALLY',
}

export enum ActivityType {
  INQUIRY = 'INQUIRY',
  INSPECTION = 'INSPECTION',
  QUOTATION = 'QUOTATION',
  SERVICE_VISIT = 'SERVICE_VISIT',
  COMPLAINT = 'COMPLAINT',
  FOLLOW_UP = 'FOLLOW_UP',
  PAYMENT = 'PAYMENT',
  RENEWAL = 'RENEWAL',
  NOTE = 'NOTE',
  STATUS_CHANGE = 'STATUS_CHANGE',
  LEAD_CONVERTED = 'LEAD_CONVERTED',
}
